log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'

  web-secure:
    # https
    address: ':443'

certificatesResolvers:
  letsencrypt:
    # https://doc.traefik.io/traefik/https/acme/#lets-encrypt
    acme:
      email: 'stevebresnick@gmail.com'
      storage: /etc/traefik/acme/acme.json
      # https://doc.traefik.io/traefik/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: 'Host(`bunklogs.net`) || Host(`www.bunklogs.net`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://doc.traefik.io/traefik/routing/routers/#certresolver
        certResolver: letsencrypt
    
    web-redirect-router:
      rule: 'Host(`bunklogs.net`) || Host(`www.bunklogs.net`)'
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: django
    
    web-localhost-router:
      rule: 'Host(`localhost`)'
      entryPoints:
        - web
      service: frontend
    
    web-localhost-secure-router:
      rule: 'Host(`localhost`)'
      entryPoints:
        - web-secure
      service: frontend
      tls: {}

  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']
    
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    django:
      loadBalancer:
        servers:
          - url: http://bunk-logs-backend:5000
    
    frontend:
      loadBalancer:
        servers:
          - url: http://bunk-logs-frontend:80

providers:
  # https://doc.traefik.io/traefik/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true