# Generated by Django 5.0.13 on 2025-05-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camperbunkassignment',
            unique_together=set(),
        ),
    ]
