services:
  - type: web
    name: bunklogs-backend
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn.conf.py config.wsgi:application"
    healthCheckPath: "/health/"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: WEB_CONCURRENCY
        value: "1"  # Use single worker for bulk operations
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
      - key: DJANGO_SECRET_KEY
        fromSecret: DJANGO_SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: bunklogs-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bunklogs-redis
          property: connectionString

databases:
  - name: bunklogs-db
    plan: starter  # or higher plan as needed

services:
  - type: redis
    name: bunklogs-redis
    plan: starter  # for caching and sessions
