/**
 * TranslationDisplay — Story 44 reader-side state machine.
 *
 * Renders an original (non-English) string alongside its server-generated
 * English translation. Handles all four states from
 * `docs/user_stories/00_cross_cutting/i18n.md`:
 *
 *   - `pending`          — translation is being generated by Celery
 *   - `completed`        — both texts available; ordered per
 *                          `Person.translation_preference`
 *   - `failed_retryable` — show original + a "Retry translation" affordance
 *   - `failed_terminal`  — show original + an "Contact Admin" copy
 *
 * The reader-preference toggle (translation-first vs. original-first) is
 * a one-click button that PATCHes `/api/v1/me/preferences/` so the choice
 * persists across sessions. Authors with no `Person` row (rare) just see
 * the local toggle take effect — the PATCH 404s silently.
 *
 * Props:
 *   - originalText       (string, required)  Source text in `sourceLanguage`.
 *   - sourceLanguage     (string, required)  e.g. "es", "he".
 *   - translation        (object | null)     The serializer-embedded
 *                                            TranslationRecord state. If
 *                                            null/undefined the original
 *                                            is rendered as-is.
 *   - onRetry            (fn, optional)      Invoked when the reader hits
 *                                            "Retry translation". Receives
 *                                            no args; caller wires it to
 *                                            POST .../retry-translation/.
 *   - initialPreference  (string, optional)  "translation_first" |
 *                                            "original_first". Falls back
 *                                            to "translation_first".
 */
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

import api from '../api';

const PREFERENCE = Object.freeze({
  TRANSLATION_FIRST: 'translation_first',
  ORIGINAL_FIRST: 'original_first',
});

const STATUS = Object.freeze({
  PENDING: 'pending',
  COMPLETED: 'completed',
  FAILED_RETRYABLE: 'failed_retryable',
  FAILED_TERMINAL: 'failed_terminal',
});

function normalizePreference(value) {
  return value === PREFERENCE.ORIGINAL_FIRST
    ? PREFERENCE.ORIGINAL_FIRST
    : PREFERENCE.TRANSLATION_FIRST;
}

export default function TranslationDisplay({
  originalText,
  sourceLanguage,
  translation,
  onRetry,
  initialPreference,
  className = '',
}) {
  const { t } = useTranslation('common');
  const [preference, setPreference] = useState(() => normalizePreference(initialPreference));
  const [retrying, setRetrying] = useState(false);

  // Pull the saved preference once. We only do this when the caller did
  // not pass `initialPreference` so embeddings inside another view that
  // already has the value can avoid an extra request.
  useEffect(() => {
    if (initialPreference) return;
    let cancelled = false;
    api
      .get('/api/v1/me/preferences/')
      .then((res) => {
        if (cancelled) return;
        const next = normalizePreference(res?.data?.translation_preference);
        setPreference(next);
      })
      .catch(() => {
        // No Person row -> fall back to translation_first (the default).
      });
    return () => {
      cancelled = true;
    };
  }, [initialPreference]);

  async function togglePreference() {
    const next =
      preference === PREFERENCE.TRANSLATION_FIRST
        ? PREFERENCE.ORIGINAL_FIRST
        : PREFERENCE.TRANSLATION_FIRST;
    setPreference(next);
    try {
      await api.patch('/api/v1/me/preferences/', { translation_preference: next });
    } catch (err) {
      if (err?.response?.status !== 404) {
        console.warn('Could not persist translation_preference', err);
      }
    }
  }

  async function handleRetry() {
    if (!onRetry || retrying) return;
    setRetrying(true);
    try {
      await onRetry();
    } finally {
      setRetrying(false);
    }
  }

  // Defensive: if the caller didn't pass any translation metadata (e.g.
  // English content), just render the original text without chrome.
  if (!translation) {
    return (
      <p className={className} data-testid="translation-display-original-only">
        {originalText}
      </p>
    );
  }

  const status = translation.status || STATUS.PENDING;
  const translatedText = translation.translated_text || '';
  const showOriginalFirst = preference === PREFERENCE.ORIGINAL_FIRST;

  const originalBlock = (
    <section
      data-testid="translation-display-original"
      lang={sourceLanguage}
      dir={sourceLanguage === 'he' ? 'rtl' : 'ltr'}
      className="rounded border border-gray-200 bg-white p-3 dark:border-gray-700 dark:bg-gray-800"
    >
      <h4 className="mb-1 text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">
        {t('translation.originalHeading')}
      </h4>
      <p className="whitespace-pre-wrap text-sm text-gray-900 dark:text-gray-100">{originalText}</p>
    </section>
  );

  const translatedBlock = (
    <section
      data-testid="translation-display-translation"
      lang="en"
      className="rounded border border-violet-200 bg-violet-50 p-3 dark:border-violet-800 dark:bg-violet-900/30"
    >
      <h4 className="mb-1 text-xs font-semibold uppercase tracking-wide text-violet-700 dark:text-violet-300">
        {t('translation.translatedHeading')}
      </h4>
      {status === STATUS.PENDING && (
        <p
          className="text-sm italic text-violet-700 dark:text-violet-200"
          data-testid="translation-display-pending"
        >
          {t('translation.pending')}
        </p>
      )}
      {status === STATUS.COMPLETED && (
        <p
          className="whitespace-pre-wrap text-sm text-gray-900 dark:text-gray-100"
          data-testid="translation-display-completed"
        >
          {translatedText}
        </p>
      )}
      {status === STATUS.FAILED_RETRYABLE && (
        <div
          className="flex flex-col gap-2 text-sm text-amber-700 dark:text-amber-300"
          data-testid="translation-display-failed-retryable"
        >
          <p>{t('translation.failedRetryable')}</p>
          {onRetry && (
            <button
              type="button"
              onClick={handleRetry}
              disabled={retrying}
              className="self-start rounded bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-800 hover:bg-amber-200 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-amber-900/40 dark:text-amber-200"
              data-testid="translation-display-retry"
            >
              {t('translation.retry')}
            </button>
          )}
        </div>
      )}
      {status === STATUS.FAILED_TERMINAL && (
        <p
          className="text-sm text-red-700 dark:text-red-300"
          data-testid="translation-display-failed-terminal"
        >
          {t('translation.failedTerminal')}
        </p>
      )}
    </section>
  );

  const blocks = showOriginalFirst
    ? [originalBlock, translatedBlock]
    : [translatedBlock, originalBlock];

  return (
    <div className={`flex flex-col gap-2 ${className}`} data-testid="translation-display">
      <div className="flex justify-end">
        <button
          type="button"
          onClick={togglePreference}
          className="text-xs font-medium text-violet-700 underline-offset-2 hover:underline dark:text-violet-300"
          data-testid="translation-display-preference-toggle"
          aria-pressed={showOriginalFirst}
        >
          {showOriginalFirst ? t('translation.preferTranslation') : t('translation.preferOriginal')}
        </button>
      </div>
      <div className="flex flex-col gap-2">
        {blocks.map((block, index) => (
          <div key={`translation-display-block-${index}`}>{block}</div>
        ))}
      </div>
    </div>
  );
}
