# Generated by Django 5.0.13 on 2026-05-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0041_subjectnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role_at_write', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=10000)),
                ('source_content_type', models.CharField(blank=True, choices=[('reflection_concern', 'Reflection concern'), ('specialist_note', 'Specialist note')], default='', max_length=32)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_platform_notes', to='core.person')),
                ('camper_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_in_platform_notes', to='core.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_notes', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_notes', to='core.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_entries', to='notes.note')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_archive_entries', to='core.person')),
            ],
            options={
                'unique_together': {('note', 'person')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_platform_notes', through='notes.NoteArchive', to='core.person'),
        ),
        migrations.CreateModel(
            name='NoteAudienceCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=64)),
                ('bunk_id_at_capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.assignmentgroup')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_captures', to='notes.note')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_audience_captures', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='NoteReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('last_read_entry_id', models.CharField(max_length=50)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='notes.note')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_read_receipts', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='NoteReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role_at_write', models.CharField(max_length=32)),
                ('body', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_replies', to='core.person')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.note')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['author', 'created_at'], name='notes_note_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='notes_note_source_idx'),
        ),
        migrations.AddIndex(
            model_name='noteaudiencecapture',
            index=models.Index(fields=['person', 'note'], name='notes_audience_person_note_idx'),
        ),
        migrations.AddIndex(
            model_name='notereadreceipt',
            index=models.Index(fields=['person', 'note'], name='notes_receipt_person_note_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notereadreceipt',
            unique_together={('note', 'person')},
        ),
        migrations.AddIndex(
            model_name='notereply',
            index=models.Index(fields=['note', 'created_at'], name='notes_reply_note_created_idx'),
        ),
    ]
