# Generated by Django 5.0.13 on 2026-05-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_core_superv_target__group_idx_core_superv_target__38854a_idx'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role_at_write', models.CharField(blank=True, default='', max_length=32)),
                ('body', models.TextField(max_length=10000)),
                ('context', models.CharField(blank=True, default='', help_text="Org-configurable context tag carried from SubjectNote (e.g. 'camper_care', 'swim_instruction').", max_length=64)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('domain', 'Domain'), ('confidential', 'Confidential')], default='normal', max_length=32)),
                ('subject_visible', models.BooleanField(default=False, help_text='When True, a tagged subject can see this observation on their own Profile.')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('he', 'Hebrew')], default='en', max_length=10)),
                ('source_content_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=50)),
                ('legacy_source', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment_of', models.ForeignKey(blank=True, help_text='Set when this observation amends an earlier one. Original is immutable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='notes.observation')),
                ('author', models.ForeignKey(blank=True, help_text='Writer. Nullable to preserve the immutable record if the Person is removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_observations', to='core.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_entries', to='notes.observation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_archive_entries', to='core.person')),
            ],
            options={
                'unique_together': {('observation', 'person')},
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_observations', through='notes.ObservationArchive', to='core.person'),
        ),
        migrations.CreateModel(
            name='ObservationSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='notes.observation')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_subject_links', to='core.person')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='observations_about', through='notes.ObservationSubject', to='core.person'),
        ),
        migrations.CreateModel(
            name='ObservationReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('last_read_entry_id', models.CharField(max_length=50)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='notes.observation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_read_receipts', to='core.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person', 'observation'], name='obs_receipt_person_obs_idx')],
                'unique_together': {('observation', 'person')},
            },
        ),
        migrations.CreateModel(
            name='ObservationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(blank=True, default='', max_length=64)),
                ('bunk_id_at_capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.assignmentgroup')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notes.observation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_recipiencies', to='core.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person', 'observation'], name='obs_recip_person_obs_idx')],
                'unique_together': {('observation', 'person')},
            },
        ),
        migrations.CreateModel(
            name='ObservationReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role_at_write', models.CharField(max_length=32)),
                ('body', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_replies', to='core.person')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.observation')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['observation', 'created_at'], name='obs_reply_obs_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='observationsubject',
            index=models.Index(fields=['subject', 'observation'], name='obs_subject_subj_obs_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='observationsubject',
            unique_together={('observation', 'subject')},
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['author', 'created_at'], name='obs_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='obs_source_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['organization', 'sensitivity', 'created_at'], name='obs_org_sens_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_source', ''), _negated=True), fields=('legacy_source',), name='obs_unique_legacy_source'),
        ),
    ]
