# Generated by Django 5.0.13 on 2026-05-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_observation_models'),
    ]

    operations = [
        migrations.DeleteModel(name='NoteReply'),
        migrations.DeleteModel(name='NoteReadReceipt'),
        migrations.DeleteModel(name='NoteAudienceCapture'),
        migrations.DeleteModel(name='NoteArchive'),
        migrations.DeleteModel(name='Note'),
    ]
