# Generated by Django 5.0.13 on 2026-06-03 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_assignmentdashboardgrant'),
        ('notes', '0004_observation_observed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-observed_at']},
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the observation occurred; defaults to submission time but may be back-dated.'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['organization', 'program', 'observed_at'], name='obs_org_prog_observed_idx'),
        ),
    ]
