# Generated by Django 5.0.13 on 2025-06-17 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0002_alter_bunk_counselors_alter_unit_unit_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='camper_care',
            field=models.ForeignKey(limit_choices_to={'role': 'Camper Care'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camper_care_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
