# Generated by Django 5.0.13 on 2025-06-17 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0003_unit_camper_care'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='camper_care',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Camper Care'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camper_care_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
