# Generated by Django 5.0.13 on 2025-06-19 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0005_bunk_is_test_data_cabin_is_test_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunk',
            name='is_test_data',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='is_test_data',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_test_data',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_test_data',
        ),
        migrations.CreateModel(
            name='UnitStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('unit_head', 'Unit Head'), ('camper_care', 'Camper Care')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='bunks.unit')),
            ],
            options={
                'verbose_name': 'unit staff assignment',
                'verbose_name_plural': 'unit staff assignments',
                'unique_together': {('unit', 'staff_member', 'role')},
            },
        ),
    ]
