# Generated by Django 5.0.13 on 2025-06-26 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0008_auto_20250626_1535'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_head',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='camper_care',
        ),
    ]
