# Generated by Django 5.0.13 on 2025-06-27 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0009_auto_20250626_1539'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorBunkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test_data', models.BooleanField(default=False, help_text='Mark this record as test/dummy data. Test data can be easily identified and deleted in bulk.', verbose_name='Is Test Data')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this counselor the primary counselor for this bunk?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_assignments', to='bunks.bunk')),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'Counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='bunk_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'counselor bunk assignment',
                'verbose_name_plural': 'counselor bunk assignments',
                'ordering': ['-start_date', '-is_primary'],
            },
        ),
        migrations.AddConstraint(
            model_name='counselorbunkassignment',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='valid_date_range_counselor_bunk'),
        ),
    ]
