# Generated by Django 5.0.13 on 2025-06-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0011_migrate_counselor_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunk',
            name='counselors',
        ),
    ]
