# Generated by Django 5.0.13 on 2025-06-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bunklogsordertypeitemcategory_is_test_data_and_more'),
        ('orders', '0002_order_additional_notes'),
    ]

    operations = [
    ]
