# Generated by Django 5.0.13 on 2025-06-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20250629_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='narrative_description',
            field=models.TextField(blank=True, help_text='Narrative description of the order', null=True),
        ),
    ]
