# Generated by Django 5.2.17 on 2026-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_narrative_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertype",
            name="item_categories",
            field=models.ManyToManyField(
                help_text="Categories of items that can be included in this order type",
                related_name="order_types",
                through="orders.BunkLogsOrderTypeItemCategory",
                through_fields=("order_type", "item_category"),
                to="orders.itemcategory",
            ),
        ),
    ]
