#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Waiting for PostgreSQL to be ready..."
python manage.py wait_for_db

echo "Running migrations..."
python manage.py migrate

echo "Collecting static files..."
python manage.py collectstatic --noinput

echo "Starting Django development server..."
exec python manage.py runserver_plus 0.0.0.0:8000
