# Generated by Django 4.2.x on 2025-01-11 xx:xx

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),  # Replace with your latest migration
    ]

    operations = [
        # Add database indexes for performance optimization
        migrations.RunSQL(
            # Create composite index for email lookups (email is already unique, but ensure it's optimized)
            "CREATE INDEX IF NOT EXISTS idx_users_user_email_active ON users_user(email, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_users_user_email_active;",
        ),
        # The legacy role indexes (idx_users_user_role, idx_users_user_role_active)
        # were removed along with the User.role column; existing databases drop
        # them in the RemoveField migration.
    ]
