# Generated by Django 4.2.x on 2025-01-11 xx:xx

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),  # Replace with your latest migration
    ]

    operations = [
        # Add database indexes for performance optimization
        migrations.RunSQL(
            # Create composite index for email lookups (email is already unique, but ensure it's optimized)
            "CREATE INDEX IF NOT EXISTS idx_users_user_email_active ON users_user(email, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_users_user_email_active;"
        ),
        migrations.RunSQL(
            # Create index for role-based queries
            "CREATE INDEX IF NOT EXISTS idx_users_user_role ON users_user(role);",
            reverse_sql="DROP INDEX IF EXISTS idx_users_user_role;"
        ),
        migrations.RunSQL(
            # Create composite index for role and active status
            "CREATE INDEX IF NOT EXISTS idx_users_user_role_active ON users_user(role, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_users_user_role_active;"
        ),
    ]
