# Generated by Django 5.0.13 on 2025-07-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_performance_indexes'),
        ('users', '0007_user_is_test_data'),
    ]

    operations = [
    ]
