# Generated by Django 5.0.13 on 2026-04-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0002_performance_indexes_0007_user_is_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
