# Generated by Django 5.0.13 on 2026-04-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Camper Care', 'Camper Care'), ('Unit Head', 'Unit Head'), ('Counselor', 'Counselor'), ('Leadership', 'Leadership'), ('Kitchen Staff', 'Kitchen Staff')], default='', max_length=255),
        ),
    ]
