# Generated by Django 5.0.13 on 2026-04-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Job title displayed in admin views (e.g. 'Associate Director').", max_length=100),
        ),
    ]
