# Generated by Django 5.0.13 on 2026-08-07 12:17
#
# Final step of the User.role retirement: the last readers were removed in
# the preceding PRs, so dropping the column is backwards-compatible with the
# currently deployed code.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_title'),
    ]

    operations = [
        # Explicitly drop the legacy role indexes created by
        # 0002_performance_indexes on databases migrated before that
        # migration was trimmed. (Dropping the column would remove them
        # anyway on Postgres; this keeps the intent visible and reversible.)
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_users_user_role;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_users_user_role_active;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
