# Generated by Django 5.0.13 on 2026-04-29 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('program_type', models.CharField(choices=[('summer_camp', 'Summer Camp'), ('religious_school', 'Religious School')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.organization')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='core_program_end_date_gte_start_date'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('organization', 'slug')},
        ),
    ]
