# Generated by Django 5.0.13 on 2026-04-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('camper', 'Camper'), ('counselor', 'Counselor'), ('junior_counselor', 'Junior Counselor'), ('specialist', 'Specialist'), ('general_counselor', 'General Counselor'), ('unit_head', 'Unit Head'), ('leadership_team', 'Leadership Team'), ('kitchen_staff', 'Kitchen Staff'), ('maintenance', 'Maintenance'), ('housekeeping', 'Housekeeping'), ('camper_care', 'Camper Care'), ('health_center', 'Health Center'), ('special_diets', 'Special Diets'), ('madrich', 'Madrich'), ('faculty', 'Faculty'), ('admin', 'Admin')], max_length=32)),
                ('grade_level', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.program')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('program', 'person', 'role')},
            },
        ),
    ]
