# Generated by Django 5.0.13 on 2026-04-30 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(blank=True, choices=[('summer_camp', 'Summer Camp'), ('religious_school', 'Religious School')], max_length=32, null=True)),
                ('role', models.CharField(blank=True, help_text='Membership role this template targets. Null = applies to all roles in program type.', max_length=32, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('on_demand', 'On Demand')], max_length=32)),
                ('schema', models.JSONField(help_text='JSON schema with localized prompts; see docs/reflection-template-schema.md')),
                ('languages', models.JSONField(blank=True, default=list, help_text="Supported language codes, e.g. ['en', 'es']")),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global template available to all orgs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_templates', to='core.organization')),
                ('parent_template', models.ForeignKey(blank=True, help_text='Previous version of this template; for version history', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.reflectiontemplate')),
            ],
            options={
                'ordering': ['organization_id', 'slug', '-version'],
                'unique_together': {('organization', 'slug', 'version')},
            },
        ),
    ]
