# Generated by Django 5.0.13 on 2026-05-01 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reflectiontemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start of period being reflected on')),
                ('period_end', models.DateField(help_text='End of period being reflected on')),
                ('answers', models.JSONField(help_text='Validated against template.schema')),
                ('language', models.CharField(default='en', help_text='Language used to fill out this reflection', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='core.person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='core.program')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Who actually submitted this reflection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections_submitted', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reflections', to='core.reflectiontemplate')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['organization', 'program', 'period_end'], name='core_reflec_organiz_9dac91_idx'), models.Index(fields=['person', 'period_end'], name='core_reflec_person__71d77a_idx'), models.Index(fields=['template', 'is_complete'], name='core_reflec_templat_ce4991_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reflection',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='core_reflection_period_end_gte_period_start'),
        ),
    ]
