# Generated by Django 5.0.13 on 2026-05-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reflection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expected_field_type', models.CharField(blank=True, help_text='Optional hint for editor: text, rating_group, etc.', max_length=32)),
                ('expected_dashboard_role', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null = global key available to all orgs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_keys', to='core.organization')),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='core_fieldk_key_fc96cc_idx')],
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
