# Generated by Django 5.0.13 on 2026-05-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fieldkey'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fieldkey',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('key',), name='core_fieldkey_global_key_unique'),
        ),
    ]
