# Generated by Django 5.0.13 on 2026-05-08 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_reflection_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignmentgroup',
            new_name='core_assign_program_87a49a_idx',
            old_name='core_assign_program_1_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentgroup',
            new_name='core_assign_parent__d5962a_idx',
            old_name='core_assign_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentgroupmembership',
            new_name='core_assign_group_i_b99d70_idx',
            old_name='core_agm_group_role_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentgroupmembership',
            new_name='core_assign_person__cf6f44_idx',
            old_name='core_agm_person_role_idx',
        ),
        migrations.RenameIndex(
            model_name='reflection',
            new_name='core_reflec_subject_492f82_idx',
            old_name='core_reflec_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='reflection',
            new_name='core_reflec_subject_81b165_idx',
            old_name='core_reflec_subj_grp_idx',
        ),
        migrations.RenameIndex(
            model_name='reflection',
            new_name='core_reflec_assignm_16c538_idx',
            old_name='core_reflec_asg_grp_idx',
        ),
        migrations.RenameIndex(
            model_name='reflection',
            new_name='core_reflec_author__3a0b79_idx',
            old_name='core_reflec_author_idx',
        ),
        migrations.RenameIndex(
            model_name='reflection',
            new_name='core_reflec_submiss_b9f906_idx',
            old_name='core_reflec_sub_id_idx',
        ),
        migrations.AlterField(
            model_name='reflection',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Who actually submitted this reflection (User; audit trail)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
