# Generated by Django 5.0.13 on 2026-05-08 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rosterimportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text="Schema field key the concern came from (e.g. 'concerns', 'overall').", max_length=64)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_read_states', to='core.reflection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'reflection'], name='core_concer_user_id_c28eb0_idx')],
                'unique_together': {('user', 'reflection', 'field_key')},
            },
        ),
    ]
