# Generated by Django 5.0.13 for the membership capability layer.
# Hand-written: adds Membership.capability as a nullable column so the column
# can be created without a table-rewrite default. 0016 backfills, 0017 enforces
# NOT NULL.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_concernreadstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="capability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("participant", "Participant"),
                    ("supervisor", "Supervisor"),
                    ("program_lead", "Program Lead"),
                    ("domain_specialist", "Domain Specialist"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                help_text="RBAC layer derived from role via ROLE_TO_CAPABILITY.",
                max_length=32,
                null=True,
            ),
        ),
    ]
