# Generated by Django 5.0.13 on 2026-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_recalibrate_camper_care_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='team_visibility',
            field=models.CharField(choices=[('team', 'Visible to team'), ('supervisors_only', 'Supervisors only')], db_index=True, default='team', help_text="Who else (beyond author + admin + ancestor-group authors + unit-scoped supervisors of the subject) can read this reflection. Default 'team' keeps peer authors in the loop; 'supervisors_only' hides it from same-group peers and from the wellness-template shortcut.", max_length=24),
        ),
    ]
