# Generated by Django 5.0.13 on 2026-05-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reflection_team_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectiontemplate',
            name='supports_privacy',
            field=models.BooleanField(default=False, help_text="Whether this template offers the per-reflection 'supervisors only' privacy toggle (Reflection.team_visibility). Off for self-reflection templates by default; on for templates where peer authors of the same AssignmentGroup would otherwise see the entry."),
        ),
    ]
