# Generated by Django 5.0.13 on 2026-05-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_backfill_template_supports_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='When true, only the sensitive-variant audience for this content type may read the reflection (author and org admin always can).', null=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('camper_care', 'Camper Care'), ('specialist', 'Specialist'), ('maintenance', 'Maintenance')], max_length=32)),
                ('body', models.TextField()),
                ('is_sensitive', models.BooleanField(default=False, help_text='Narrows audience per the visibility model sensitive-variant table.', null=True)),
                ('maintenance_visibility', models.CharField(blank=True, choices=[('team_only', 'Team only'), ('submitter_visible', 'Submitter and team')], default='team_only', help_text='Only used when note_type is maintenance.', max_length=32)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_authored', to='core.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_about', to='core.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'program', 'subject', 'created_at'], name='core_note_organiz_d1b34f_idx'), models.Index(fields=['note_type', 'is_sensitive'], name='core_note_note_ty_4cdb83_idx')],
            },
        ),
    ]
