# Generated by Django 5.0.13 on 2026-05-20 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_reflection_is_sensitive_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('unable_to_fulfill', 'Unable to Fulfill')], db_index=True, default='new', max_length=24)),
                ('urgency', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='', help_text='Optional priority. Used by Maintenance tickets; left blank for Camper Care orders unless the program opts in.', max_length=16)),
                ('last_transition_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('urgent_reason', models.TextField(blank=True, help_text="Required by API when urgency is 'urgent' (Story 32).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transition_by', models.ForeignKey(blank=True, help_text='Membership of the actor who applied the most recent transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='core.program')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets_submitted', to='core.membership')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'program', 'status'], name='core_mainte_organiz_4cf104_idx'), models.Index(fields=['urgency', 'status', 'created_at'], name='core_mainte_urgency_d2aeca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('unable_to_fulfill', 'Unable to Fulfill')], db_index=True, default='new', max_length=24)),
                ('urgency', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='', help_text='Optional priority. Used by Maintenance tickets; left blank for Camper Care orders unless the program opts in.', max_length=16)),
                ('last_transition_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transition_by', models.ForeignKey(blank=True, help_text='Membership of the actor who applied the most recent transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_orders', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_orders', to='core.program')),
                ('subject', models.ForeignKey(blank=True, help_text='Camper this order is for. Null when the order is bunk-scoped only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_orders_about', to='core.person')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Membership of the counselor / submitter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_orders_submitted', to='core.membership')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'program', 'status'], name='core_order_organiz_6385c0_idx'), models.Index(fields=['status', 'created_at'], name='core_order_status_273d1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('state_change', 'State change'), ('correction', 'Correction (within 5-minute window)'), ('note', 'Note (no state change)')], db_index=True, max_length=24)),
                ('content_type', models.CharField(help_text="Stable label for the related model (e.g. 'order', 'maintenance_ticket').", max_length=64)),
                ('content_id', models.UUIDField()),
                ('from_state', models.CharField(blank=True, max_length=24)),
                ('to_state', models.CharField(blank=True, max_length=24)),
                ('note', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_activity_events', to='core.membership')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_activity_events', to=settings.AUTH_USER_MODEL)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='core.orderactivityevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_activity_events', to='core.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_activity_events', to='core.program')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id', 'created_at'], name='core_ordera_content_afc974_idx'), models.Index(fields=['organization', 'created_at'], name='core_ordera_organiz_419f0a_idx')],
            },
        ),
    ]
