# Generated by Django 5.0.13 on 2026-05-20 00:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_maintenanceticket_order_orderactivityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('membership', 'Membership (direct supervisee)'), ('role_in_program', 'Role in program (team-by-role)'), ('bunk', 'Bunk (caseload entry)')], db_index=True, max_length=24)),
                ('target_role', models.CharField(blank=True, default='', help_text='Target Membership.role string when target_type=ROLE_IN_PROGRAM. Must be one of Membership.ROLES.', max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor_membership', models.ForeignKey(help_text='Membership of the supervising role.', on_delete=django.db.models.deletion.CASCADE, related_name='supervises', to='core.membership')),
                ('target_bunk', models.ForeignKey(blank=True, help_text="AssignmentGroup with group_type='bunk' when target_type=BUNK. Spec uses 'Bunk' as shorthand; new code targets AssignmentGroup.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caseload_supervisions', to='core.assignmentgroup')),
                ('target_membership', models.ForeignKey(blank=True, help_text='Target Membership when target_type=MEMBERSHIP.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_by', to='core.membership')),
                ('target_program', models.ForeignKey(blank=True, help_text='Program scoping the role; required when target_type=ROLE_IN_PROGRAM.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisions_scoped_to_role', to='core.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Supervision created'), ('modified', 'Supervision modified'), ('ended', 'Supervision ended')], db_index=True, max_length=24)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_events_actor', to='core.membership')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_events', to='core.organization')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.supervision')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supervision',
            index=models.Index(fields=['supervisor_membership', 'target_type'], name='core_superv_supervi_44579a_idx'),
        ),
        migrations.AddIndex(
            model_name='supervision',
            index=models.Index(fields=['target_membership'], name='core_superv_target__9205c5_idx'),
        ),
        migrations.AddIndex(
            model_name='supervision',
            index=models.Index(fields=['target_program', 'target_role'], name='core_superv_target__308eab_idx'),
        ),
        migrations.AddIndex(
            model_name='supervision',
            index=models.Index(fields=['target_bunk'], name='core_superv_target__b6c4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='supervision',
            index=models.Index(fields=['start_date', 'end_date'], name='core_superv_start_d_d6dfd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='supervision',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='core_supervision_end_date_gte_start_date'),
        ),
        migrations.AddIndex(
            model_name='supervisionevent',
            index=models.Index(fields=['supervision', 'created_at'], name='core_superv_supervi_9ccfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionevent',
            index=models.Index(fields=['organization', 'created_at'], name='core_superv_organiz_4882fa_idx'),
        ),
    ]
