# Generated by Django 5.0.13 on 2026-05-20 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_supervision_supervisionevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('state_changed', 'State changed'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('override_edit', 'Admin override: edit'), ('override_close', 'Admin override: close'), ('override_resolve', 'Admin override: resolve'), ('audit_view', 'Audit view (meta)'), ('export', 'Export')], db_index=True, max_length=24)),
                ('content_type', models.CharField(help_text="Stable label for the related model (e.g. 'order', 'reflection').", max_length=64)),
                ('content_id', models.CharField(blank=True, default='', help_text='Primary key of the related content row, serialised as a string. UUID-keyed content (Order, MaintenanceTicket) stores the UUID; int-keyed content (Reflection, Note, Supervision) stores the integer id. Synthetic events (e.g. EXPORT) may store an empty string.', max_length=64)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('reason_note', models.TextField(blank=True, default='')),
                ('is_admin_override', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_membership', models.ForeignKey(blank=True, help_text='Membership of the user who performed the action. Null for platform-support / migration writes that have no in-app actor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.membership')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who performed the action -- captured even when no active Membership exists (e.g. Super Admins without an org admin row).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.program')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id', 'created_at'], name='core_audite_content_690cb9_idx'), models.Index(fields=['organization', 'created_at'], name='core_audite_organiz_79e83d_idx'), models.Index(fields=['actor_membership', 'created_at'], name='core_audite_actor_m_878c27_idx'), models.Index(fields=['event_type', 'created_at'], name='core_audite_event_t_68fb24_idx'), models.Index(fields=['is_admin_override', 'created_at'], name='core_audite_is_admi_4f611c_idx')],
            },
        ),
    ]
