# Generated by Django 5.0.13 on 2026-05-20 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='translation_preference',
            field=models.CharField(choices=[('translation_first', 'Translation first'), ('original_first', 'Original first')], default='translation_first', help_text="Per-reader preference for bilingual content (Story 44 criterion 6). Stored on Person so it persists across sessions. Only affects rendering when the content's language differs from English.", max_length=24),
        ),
        migrations.AlterField(
            model_name='note',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('he', 'Hebrew')], default='en', help_text='Language used to author this note. Non-English notes trigger the server-side auto-translation task once the Note edit views land (Steps 7_8 / 7_9 / 7_10).', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('he', 'Hebrew')], default='en', help_text='Preferred language for UI + email communications. Tier 1 ships English + Spanish UI; Hebrew renders natively (עברית) in the language picker but the surrounding UI stays English -- see docs/user_stories/00_cross_cutting/i18n.md.', max_length=10),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('he', 'Hebrew')], default='en', help_text='Language used to fill out this reflection. Non-English submissions trigger the server-side auto-translation task (see ``bunk_logs.core.translation``).', max_length=10),
        ),
        migrations.CreateModel(
            name='TranslationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(help_text="Stable label for the translated model ('reflection' or 'note').", max_length=64)),
                ('content_id', models.CharField(help_text='PK of the translated content row, serialised as a string -- matches the ``AuditEvent.content_id`` convention.', max_length=64)),
                ('source_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('he', 'Hebrew')], help_text="ISO code of the original content language ('es' or 'he').", max_length=10)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('he', 'Hebrew')], default='en', help_text='ISO code of the translation target. Tier 1 is English-only.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed_retryable', 'Failed (retrying)'), ('failed_terminal', 'Failed (terminal)')], db_index=True, default='pending', max_length=24)),
                ('translated_text', models.TextField(blank=True, default='', help_text="English translation. Empty while ``status='pending'``.")),
                ('model_id', models.CharField(blank=True, default='', help_text="Identifier of the Anthropic model that produced the translation (e.g. 'claude-sonnet-4-5'). Captured for reproducibility.", max_length=128)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total input+output tokens reported by the Anthropic response.')),
                ('last_error', models.TextField(blank=True, default='', help_text='Exception message captured on the most recent failed attempt.')),
                ('celery_task_id', models.CharField(blank=True, default='', help_text='Currently-enqueued Celery task id, so re-translation on edit can revoke the pending task before queueing a fresh one.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_records', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id', '-created_at'], name='core_transl_content_030b9d_idx'), models.Index(fields=['status', 'created_at'], name='core_transl_status_4f1656_idx'), models.Index(fields=['organization', 'created_at'], name='core_transl_organiz_bbe645_idx')],
            },
        ),
    ]
