# Generated by Django 5.0.13 on 2026-05-20 15:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import bunk_logs.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_register_translation_purge_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CamperDayState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Operational date (per org rollover). One row per camper per date.")),
                ("is_off_camp", models.BooleanField(default=False, help_text="True when the camper is marked off-camp for the date.")),
                ("reason", models.TextField(blank=True, default="", help_text="Optional context (e.g. 'home visit', 'medical leave'). Visible to UH, Camper Care, Leadership Team, Admin -- not surfaced to Counselors in the roster row.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "camper_id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItemSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(help_text="Canonical display label, e.g. 'Toothbrush'.", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0, help_text="Lower numbers appear first; ties break alphabetically.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="TicketPhoto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(max_length=512, upload_to=bunk_logs.core.models.maintenance_ticket_photo_upload_path)),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("is_followup", models.BooleanField(default=False, help_text="True for photos added after the ticket was first submitted (decision C5: Counselors can add follow-up photos).")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="maintenanceticket",
            name="category",
            field=models.CharField(blank=True, choices=[("plumbing", "Clogged plumbing"), ("broken_light", "Broken light"), ("pest", "Pest / Insect"), ("leak", "Leak"), ("other", "Other")], default="", help_text="Triage category (Story 8 criterion 1.ii).", max_length=24),
        ),
        migrations.AddField(
            model_name="maintenanceticket",
            name="client_submission_id",
            field=models.UUIDField(blank=True, db_index=True, help_text="Client-supplied idempotency key (Step 7_6 Story 8 criterion 4). Unique with ``program`` so the offline queue can replay safely.", null=True),
        ),
        migrations.AddField(
            model_name="maintenanceticket",
            name="location",
            field=models.CharField(blank=True, default="", help_text="Free-text camp location (Story 8 criterion 1.i). Defaults to the submitter's bunk on the client; persisted as the canonical value submitted so renames of bunks don't rewrite history.", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="client_submission_id",
            field=models.UUIDField(blank=True, db_index=True, help_text="Client-supplied idempotency key (Step 7_6 Story 7 criterion 6). Unique with ``program`` so the offline queue can replay safely.", null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.CharField(blank=True, default="", help_text="Camper-care item requested (Story 7 criterion 2.ii). Free-text with autocomplete on the client against ``OrderItemSuggestion`` rows; the canonical value is stored here so admins maintaining the suggestion list don't retroactively rewrite history.", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="item_note",
            field=models.TextField(blank=True, default="", help_text="Optional note from the requester (Story 7 criterion 2.iii)."),
        ),
        migrations.AddField(
            model_name="reflection",
            name="client_submission_id",
            field=models.UUIDField(blank=True, db_index=True, help_text="Client-supplied idempotency key (Step 7_6 Story 7 criterion 6). The frontend offline queue retries POSTs after reconnect; the API short-circuits duplicates by returning the existing row when (program, client_submission_id) already exists. Null for server-side / legacy creations.", null=True),
        ),
        migrations.AlterField(
            model_name="maintenanceticket",
            name="urgent_reason",
            field=models.TextField(blank=True, help_text="Required by API when urgency is 'urgent' (Story 8 criterion 2)."),
        ),
        migrations.AddConstraint(
            model_name="maintenanceticket",
            constraint=models.UniqueConstraint(condition=models.Q(("client_submission_id__isnull", False)), fields=("program", "client_submission_id"), name="core_maintenance_client_submission_unique"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(condition=models.Q(("client_submission_id__isnull", False)), fields=("program", "client_submission_id"), name="core_order_client_submission_unique"),
        ),
        migrations.AddConstraint(
            model_name="reflection",
            constraint=models.UniqueConstraint(condition=models.Q(("client_submission_id__isnull", False)), fields=("program", "client_submission_id"), name="core_reflection_client_submission_unique"),
        ),
        migrations.AddField(
            model_name="camperdaystate",
            name="camper",
            field=models.ForeignKey(help_text="The camper (Person) whose state this row records.", on_delete=django.db.models.deletion.CASCADE, related_name="day_states", to="core.person"),
        ),
        migrations.AddField(
            model_name="camperdaystate",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="camper_day_states", to="core.organization"),
        ),
        migrations.AddField(
            model_name="camperdaystate",
            name="program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="camper_day_states", to="core.program"),
        ),
        migrations.AddField(
            model_name="camperdaystate",
            name="set_by_membership",
            field=models.ForeignKey(blank=True, help_text="Membership of the UH / Camper Care who toggled the flag.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="camper_day_states_set", to="core.membership"),
        ),
        migrations.AddField(
            model_name="orderitemsuggestion",
            name="program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="order_item_suggestions", to="core.program"),
        ),
        migrations.AddField(
            model_name="ticketphoto",
            name="ticket",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="core.maintenanceticket"),
        ),
        migrations.AddField(
            model_name="ticketphoto",
            name="uploaded_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_ticket_photos_uploaded", to="core.membership"),
        ),
        migrations.AddIndex(
            model_name="camperdaystate",
            index=models.Index(fields=["program", "date", "is_off_camp"], name="core_camper_program_869fcb_idx"),
        ),
        migrations.AddIndex(
            model_name="camperdaystate",
            index=models.Index(fields=["camper", "date"], name="core_camper_camper__f9b931_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="camperdaystate",
            unique_together={("organization", "camper", "date")},
        ),
        migrations.AddIndex(
            model_name="orderitemsuggestion",
            index=models.Index(fields=["program", "is_active", "sort_order"], name="core_orderi_program_3097ba_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="orderitemsuggestion",
            unique_together={("program", "label")},
        ),
        migrations.AddIndex(
            model_name="ticketphoto",
            index=models.Index(fields=["ticket", "created_at"], name="core_ticket_ticket__d511c8_idx"),
        ),
    ]
