# Generated by Django 5.0.13 on 2026-05-21 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_unit_head_self_reflection_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('family', 'Family'), ('social', 'Social'), ('behavioral', 'Behavioral'), ('other', 'Other')], default='', help_text="Camper Care note category (Story 21 criterion 2). Required by the Camper Care write endpoint; left blank for specialist / maintenance notes that don't use the enum.", max_length=16),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flagged_for_role', models.CharField(default='camper_care', help_text='Role responsible for triaging this flag. Tier 1 only routes to ``camper_care``; future expansion keeps the field open.', max_length=32)),
                ('trigger_content_type', models.CharField(blank=True, default='', help_text='Stable label of the model that raised the flag (e.g. ``specialist_note``, ``reflection``).', max_length=64)),
                ('trigger_content_id', models.CharField(blank=True, default='', help_text='PK of the trigger row, serialised as a string.', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('followed_up', 'Followed Up'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.program')),
                ('raised_by_membership', models.ForeignKey(blank=True, help_text='Membership of the role who raised this flag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_raised', to='core.membership')),
                ('resolved_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to='core.membership')),
                ('subject_camper', models.ForeignKey(help_text='The camper this flag is raised on.', on_delete=django.db.models.deletion.CASCADE, related_name='flags_about', to='core.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'program', 'status'], name='core_flag_organiz_c24832_idx'), models.Index(fields=['subject_camper', 'status'], name='core_flag_subject_45619f_idx'), models.Index(fields=['flagged_for_role', 'status', 'created_at'], name='core_flag_flagged_fa6510_idx')],
            },
        ),
    ]
