# Generated by Django 5.0.13 on 2026-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_reflectiontemplate_status_templateassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectiontemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Free-form bag of admin-level annotations. Currently used by Step 7_13 PR3 to store Admin review status (``review_status`` is 'reviewed' or 'needs_revision' plus reviewed_at / reviewed_by_membership_id / review_note). Schema definition is documented in ``docs/role_flows/admin.md`` rather than here so future annotations don't require a column migration."),
        ),
        migrations.AddField(
            model_name='reflectiontemplate',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text="When the template most recently transitioned to 'published'. Used by the Admin Templates oversight surface (Step 7_13 PR3, Story 57) to highlight templates published in the last 14 days that haven't yet been marked as reviewed.", null=True),
        ),
    ]
