# Generated by Django 5.0.13 on 2026-05-26 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_templateassignment_assignment_group_is_required_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, default='', help_text="Org-configurable context tag for the observation context. Examples: 'swim_instruction', 'wellness_checkin', 'camper_care'. Free text; validated values can be stored in Organization.settings.", max_length=64)),
                ('body', models.TextField(help_text='Note text.')),
                ('visibility', models.CharField(choices=[('team', 'Team'), ('supervisors_only', 'Supervisors Only'), ('domain_only', 'Domain Specialists Only'), ('admin_only', 'Admin Only')], default='supervisors_only', help_text="Who can read this note. 'team' = anyone with dashboard access; 'supervisors_only' = supervisors and above (default); 'domain_only' = domain specialists and above; 'admin_only' = admins only.", max_length=32)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Extra read-access restriction (same semantics as Reflection.is_sensitive).')),
                ('subject_visible', models.BooleanField(default=False, help_text='When True, the subject can see this note on their own dashboard regardless of visibility level.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment_of', models.ForeignKey(blank=True, help_text='Set when this note is an amendment to an earlier note. Original is immutable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='core.subjectnote')),
                ('author_person', models.ForeignKey(blank=True, help_text='Person who wrote the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_notes_authored', to='core.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_notes', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_notes', to='core.program')),
                ('subject', models.ForeignKey(help_text='Who this note is about.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_notes_about', to='core.person')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who clicked submit (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_notes_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'program', 'created_at'], name='snote_subj_prog_created_idx'), models.Index(fields=['organization', 'created_at'], name='snote_org_created_idx')],
            },
        ),
    ]
