# Generated by Django 5.0.13 on 2026-05-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_supervision_group_target'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supervision',
            new_name='core_superv_target__38854a_idx',
            old_name='core_superv_target__group_idx',
        ),
    ]
