# Generated by Django 5.0.13 on 2026-05-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_core_superv_target__group_idx_core_superv_target__38854a_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectnote',
            name='amendment_of',
        ),
        migrations.RemoveField(
            model_name='subjectnote',
            name='author_person',
        ),
        migrations.RemoveField(
            model_name='subjectnote',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='subjectnote',
            name='program',
        ),
        migrations.RemoveField(
            model_name='subjectnote',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectnote',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='SubjectNote',
        ),
    ]
