# Generated by Django 5.0.13 on 2026-06-02 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_subjectnote_amendment_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDashboardGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_grants', to='core.templateassignment')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_dashboard_grants_made', to='core.membership')),
                ('membership', models.ForeignKey(help_text="The grantee — this Membership's Person can view the assignment dashboard.", on_delete=django.db.models.deletion.CASCADE, related_name='assignment_dashboard_grants', to='core.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_dashboard_grants', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'membership'], name='core_assign_organiz_65db21_idx')],
                'unique_together': {('assignment', 'membership')},
            },
        ),
    ]
