# Generated by Django 5.0.13 on 2026-05-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_notereply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectNoteReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role_at_write', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_note_replies', to='core.person')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.subjectnote')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['note', 'created_at'], name='core_subjec_note_id_ab0926_idx')],
            },
        ),
    ]
