# Generated by Django 5.0.13 on 2026-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_order_submitted_from_bunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('camper', 'Camper'), ('counselor', 'Counselor'), ('junior_counselor', 'Junior Counselor'), ('specialist', 'Specialist'), ('general_counselor', 'General Counselor'), ('unit_head', 'Unit Head'), ('leadership_team', 'Leadership Team'), ('kitchen_staff', 'Kitchen Staff'), ('maintenance', 'Maintenance'), ('administrative_staff', 'Administrative Staff'), ('housekeeping', 'Housekeeping'), ('camper_care', 'Camper Care'), ('health_center', 'Health Center'), ('medical', 'Medical'), ('special_diets', 'Special Diets'), ('madrich', 'Madrich'), ('faculty', 'Faculty'), ('admin', 'Admin')], max_length=32),
        ),
    ]
