# Generated by Django 5.0.13 on 2026-06-25 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_register_maintenance_digest_dispatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_request_types', to='core.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Canonical label, e.g. 'Toothbrush'.", max_length=120)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('track_quantity', models.BooleanField(default=True, help_text='False for services (count requests); True for consumables (sum quantities).')),
                ('unit', models.CharField(blank=True, default='', help_text="Optional unit for quantities, e.g. 'roll', 'bottle'.", max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='core.organization')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.requesttype')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Canonical name, e.g. 'Maintenance'.", max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('labels', models.JSONField(blank=True, default=dict, help_text="Localized labels, e.g. {'en': 'Maintenance', 'es': 'Mantenimiento'}.")),
                ('fulfilling_role', models.CharField(choices=[('camper_care', 'Camper Care'), ('maintenance', 'Maintenance')], help_text="Team that fulfils this store's requests.", max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_stores', to='core.organization')),
                ('program', models.ForeignKey(blank=True, help_text='Narrow this store to one program; null = org-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_stores', to='core.program')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='requesttype',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_types', to='core.store'),
        ),
        migrations.CreateModel(
            name='RequestLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_label', models.CharField(help_text='Snapshot of the item label at submission time.', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, help_text='Catalog item; null for free-text entries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='core.catalogitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_line_items', to='core.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.maintenanceticket')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['organization', 'item'], name='core_reques_organiz_c60620_idx'), models.Index(fields=['order'], name='core_reques_order_i_2c042c_idx'), models.Index(fields=['ticket'], name='core_reques_ticket__336325_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='requestlineitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order__isnull', False), ('ticket__isnull', True)), models.Q(('order__isnull', True), ('ticket__isnull', False)), _connector='OR'), name='core_requestlineitem_exactly_one_parent'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['organization', 'is_active', 'sort_order'], name='core_catalo_organiz_605b26_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['request_type', 'is_active', 'sort_order'], name='core_catalo_request_789802_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('request_type', 'name'), name='core_catalogitem_type_name_unique'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['organization', 'is_active', 'sort_order'], name='core_store_organiz_4f3f5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='core_store_org_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='requesttype',
            index=models.Index(fields=['organization', 'is_active', 'sort_order'], name='core_reques_organiz_890f47_idx'),
        ),
        migrations.AddConstraint(
            model_name='requesttype',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='core_requesttype_store_slug_unique'),
        ),
    ]
