# Generated by Django 5.0.13 on 2026-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_seed_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='category',
            field=models.CharField(blank=True, choices=[('plumbing', 'Clogged plumbing'), ('broken_light', 'Broken light'), ('pest', 'Pest / Insect'), ('leak', 'Leak'), ('other', 'Other')], default='', help_text='Triage category (Story 8 criterion 1.ii). Stores either a legacy enum value (mapped to a label by get_category_display) or a configurable catalog item label. Widened from 24 chars in Step 7_catalog to hold longer admin-defined service labels.', max_length=120),
        ),
    ]
