# Generated by Django 5.0.13 on 2026-07-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_richtextimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maintenance ticket', 'verbose_name_plural': 'Maintenance tickets'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Camper Care order', 'verbose_name_plural': 'Camper Care orders'},
        ),
    ]
