# Generated by Django 5.0.13 on 2026-08-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_organization_branding_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadrichAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='A program session Sunday.')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('tentative', 'Tentative')], max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madrich_availabilities', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_commitments', to='core.person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madrich_availabilities', to='core.program')),
            ],
            options={
                'ordering': ['session_date'],
                'indexes': [models.Index(fields=['program', 'session_date'], name='core_madric_program_933cd1_idx'), models.Index(fields=['person', 'session_date'], name='core_madric_person__35eaea_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='madrichavailability',
            constraint=models.UniqueConstraint(fields=('program', 'person', 'session_date'), name='uniq_madrich_availability_per_session'),
        ),
    ]
