# Generated by Django 5.0.13 on 2026-08-12 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_madrich_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(help_text='Sunday session this challenge pertains to; defaults to upcoming or current session.')),
                ('category', models.CharField(choices=[('behavior', 'Student behavior'), ('environment', 'Room environment'), ('schedule', 'Schedule / timing'), ('materials', 'Materials / curriculum'), ('other', 'Other')], max_length=32)),
                ('body', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_group', models.ForeignKey(limit_choices_to={'group_type': 'classroom'}, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.assignmentgroup')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_challenges_authored', to='core.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_challenges', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_challenges', to='core.program')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_challenges_resolved', to='core.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomChallengeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_challenge_responses', to='core.person')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.classroomchallenge')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomchallenge',
            index=models.Index(fields=['assignment_group', 'session_date', 'status'], name='core_classr_assignm_739c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomchallenge',
            index=models.Index(fields=['program', 'created_at'], name='core_classr_program_826c75_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomchallenge',
            index=models.Index(fields=['author', 'created_at'], name='core_classr_author__6327c9_idx'),
        ),
    ]
