# Generated by Django 5.0.13 on 2026-08-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_tbe_madrich_template_thread_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64)),
                ('item_index', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(max_length=10000)),
                ('is_hidden', models.BooleanField(default=False, help_text='Soft, reversible director moderation; see CohortShareModeration for the who/when.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_group', models.ForeignKey(blank=True, help_text='Cohort this was shared into; null means the program-wide feed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_shares', to='core.assignmentgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_shares', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_shares', to='core.person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_shares', to='core.program')),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_shares', to='core.reflection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortShareModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'Hide'), ('unhide', 'Unhide')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_share_moderations', to='core.person')),
                ('cohort_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to='core.cohortshare')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, default='', max_length=64)),
                ('item_index', models.IntegerField(blank=True, help_text='Index within a text_list answer; null when the whole field threads as one.', null=True)),
                ('routes_to', models.CharField(blank=True, choices=[('faculty', 'Faculty'), ('director', 'Director'), ('both', 'Faculty and Director')], default='', help_text='Snapshot of the schema flag at submit time; blank means unrouted.', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('cohort_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.cohortshare')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_threads', to='core.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_threads', to='core.program')),
                ('reflection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.reflection')),
                ('subject_person', models.ForeignKey(help_text='Whose entry this thread hangs off.', on_delete=django.db.models.deletion.CASCADE, related_name='threads_about_me', to='core.person')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('like', 'Like')], default='like', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.cohortshare')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_reactions', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role_at_write', models.CharField(blank=True, default='', help_text="Snapshot of the author's Membership role when the message was written.", max_length=32)),
                ('body', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_messages', to='core.person')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.entrythread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_reads', to='core.person')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.entrythread')),
            ],
        ),
        migrations.AddIndex(
            model_name='cohortshare',
            index=models.Index(fields=['organization', 'program', 'created_at'], name='core_cohort_organiz_cc37ce_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortshare',
            index=models.Index(fields=['assignment_group', 'created_at'], name='core_cohort_assignm_317340_idx'),
        ),
        migrations.AddConstraint(
            model_name='cohortshare',
            constraint=models.UniqueConstraint(fields=('reflection', 'field_key', 'item_index'), name='uniq_cohort_share_per_reflection_entry'),
        ),
        migrations.AddIndex(
            model_name='entrythread',
            index=models.Index(fields=['organization', 'program', 'routes_to', 'resolved_at'], name='core_entryt_organiz_e26f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='entrythread',
            index=models.Index(fields=['subject_person', 'last_message_at'], name='core_entryt_subject_05d5e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrythread',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cohort_share__isnull', True), ('reflection__isnull', False)), models.Q(('cohort_share__isnull', False), ('reflection__isnull', True)), _connector='OR'), name='entry_thread_exactly_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='entrythread',
            constraint=models.UniqueConstraint(condition=models.Q(('reflection__isnull', False)), fields=('reflection', 'field_key', 'item_index'), name='uniq_entry_thread_per_reflection_entry'),
        ),
        migrations.AlterUniqueTogether(
            name='sharereaction',
            unique_together={('cohort_share', 'person', 'kind')},
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread', 'created_at'], name='core_thread_thread__88f289_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadread',
            unique_together={('thread', 'person')},
        ),
    ]
